<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello.proto

namespace GPBMetadata;

class Hello
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xF5\x02\x0A\x0Bhello.proto\x12\x05myapp\"\x1C\x0A\x0CHelloRequest\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\" \x0A\x0DHelloResponse\x12\x0F\x0A\x07message\x18\x01 \x01(\x092\x8A\x02\x0A\x0FGreetingService\x122\x0A\x05Hello\x12\x13.myapp.HelloRequest\x1A\x14.myapp.HelloResponse\x12@\x0A\x11HelloServerStream\x12\x13.myapp.HelloRequest\x1A\x14.myapp.HelloResponse0\x01\x12@\x0A\x11HelloClientStream\x12\x13.myapp.HelloRequest\x1A\x14.myapp.HelloResponse(\x01\x12?\x0A\x0EHelloBiStreams\x12\x13.myapp.HelloRequest\x1A\x14.myapp.HelloResponse(\x010\x01B\x0AZ\x08pkg/grpcb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

