FROM php:8.4-fpm-alpine

# 必要な拡張をインストール
RUN apk add --no-cache \
    unzip \
    git \
    protobuf \
    $PHPIZE_DEPS \
    zlib-dev

RUN pecl install grpc protobuf
RUN docker-php-ext-enable grpc protobuf

# Composerのインストール
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# アプリケーションコードをコピー
WORKDIR /app
COPY . /app

# 依存関係のインストール
RUN composer install

CMD ["php", "/app/server.php"]